const BASE_URL = "https://www.funappbox.com";

const routes = [
  { path: "/", priority: 1.0, changeFrequency: "weekly" },
  { path: "/about", priority: 0.6, changeFrequency: "monthly" },
  { path: "/privacy", priority: 0.5, changeFrequency: "yearly" },
  { path: "/terms", priority: 0.5, changeFrequency: "yearly" },
  { path: "/contact", priority: 0.6, changeFrequency: "monthly" },
  { path: "/blog", priority: 0.8, changeFrequency: "weekly" },
  { path: "/blog/mbti-16-types-guide", priority: 0.7, changeFrequency: "monthly" },
  { path: "/blog/saju-basics", priority: 0.7, changeFrequency: "monthly" },
  { path: "/blog/korean-spelling-50", priority: 0.7, changeFrequency: "monthly" },
  { path: "/blog/investing-backtesting", priority: 0.7, changeFrequency: "monthly" },
  { path: "/blog/wcag-color-contrast", priority: 0.7, changeFrequency: "monthly" },
  { path: "/blog/password-security-guide", priority: 0.7, changeFrequency: "monthly" },
  { path: "/blog/korean-age-system", priority: 0.7, changeFrequency: "monthly" },
  { path: "/blog/focus-sounds-science", priority: 0.7, changeFrequency: "monthly" },
  { path: "/name-test", priority: 0.9, changeFrequency: "monthly" },
  { path: "/calculator", priority: 0.9, changeFrequency: "monthly" },
  { path: "/mbti", priority: 0.9, changeFrequency: "monthly" },
  { path: "/spelling", priority: 0.8, changeFrequency: "monthly" },
  { path: "/sound", priority: 0.8, changeFrequency: "monthly" },
  { path: "/invest", priority: 0.8, changeFrequency: "monthly" },
  { path: "/color", priority: 0.8, changeFrequency: "monthly" },
  { path: "/typing", priority: 0.8, changeFrequency: "monthly" },
  { path: "/menu", priority: 0.8, changeFrequency: "monthly" },
  { path: "/dday", priority: 0.8, changeFrequency: "monthly" },
  { path: "/snake", priority: 0.7, changeFrequency: "monthly" },
  { path: "/flappy", priority: 0.7, changeFrequency: "monthly" },
  { path: "/hamster", priority: 0.8, changeFrequency: "monthly" },
  { path: "/fortune", priority: 0.9, changeFrequency: "daily" },
  { path: "/balance", priority: 0.8, changeFrequency: "monthly" },
  { path: "/qrcode", priority: 0.9, changeFrequency: "monthly" },
  { path: "/game2048", priority: 0.7, changeFrequency: "monthly" },
  { path: "/charcount", priority: 0.9, changeFrequency: "monthly" },
  { path: "/animal-test", priority: 0.8, changeFrequency: "monthly" },
  { path: "/age-calc", priority: 0.9, changeFrequency: "monthly" },
  { path: "/password", priority: 0.8, changeFrequency: "monthly" },
  { path: "/wordle-kr", priority: 0.8, changeFrequency: "daily" },
  { path: "/past-life", priority: 0.7, changeFrequency: "monthly" },
  { path: "/tarot", priority: 0.8, changeFrequency: "monthly" },
  { path: "/minesweeper", priority: 0.7, changeFrequency: "monthly" },
  { path: "/tictactoe", priority: 0.7, changeFrequency: "monthly" },
  { path: "/unit-convert", priority: 0.9, changeFrequency: "monthly" },
];

export default function sitemap() {
  const today = new Date().toISOString().slice(0, 10);
  return routes.map((route) => ({
    url: `${BASE_URL}${route.path}`,
    lastModified: today,
    changeFrequency: route.changeFrequency,
    priority: route.priority,
  }));
}
